spring:
  application:
    name: career-log

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/career_log}
    username: ${SPRING_DATASOURCE_USERNAME:career}
    password: ${SPRING_DATASOURCE_PASSWORD:career1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080