spring:
  application:
    name: career-log

  datasource:
    url: jdbc:postgresql://localhost:5432/career_log
    username: career
    password: career1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080